import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#4d5557",
        "surface-container-highest": "#e1e2e8",
        outline: "#71787f",
        "on-tertiary-fixed": "#151d1f",
        "surface-container-high": "#e7e8ee",
        "inverse-on-surface": "#eff0f6",
        "primary-fixed-dim": "#8fcdff",
        "surface-container-low": "#eff4ff",
        "primary-container": "#2872a1",
        "on-primary-fixed-variant": "#004b71",
        "on-primary-container": "#94cfff",
        "on-tertiary-fixed-variant": "#40484a",
        "surface-tint": "#196490",
        background: "#f8f9ff",
        "on-background": "#191c20",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#0c1e26",
        "on-surface-variant": "#41484e",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c0c8ca",
        "surface-dim": "#d8dae0",
        "error-container": "#ffdad6",
        tertiary: "#363e40",
        "on-tertiary": "#ffffff",
        surface: "#f8f9ff",
        "inverse-surface": "#2e3135",
        "tertiary-fixed": "#dce4e6",
        "surface-bright": "#f8f9ff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#c1c9cb",
        "on-primary-fixed": "#001e30",
        secondary: "#50616b",
        "dark-surface": "#1e293b",
        "on-surface": "#191c20",
        "outline-variant": "#c0c7d0",
        "inverse-primary": "#8fcdff",
        "surface-container": "#eceef3",
        "primary-fixed": "#cbe6ff",
        "dark-card": "#273549",
        "secondary-fixed-dim": "#b7c9d5",
        "secondary-fixed": "#d3e5f1",
        "on-error-container": "#93000a",
        primary: "#004162",
        "secondary-container": "#d0e2ee",
        "on-secondary-container": "#54656f",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#384953",
        "surface-variant": "#e1e2e8",
        "dark-background": "#0f172a",
        "status-passed": "#10b981",
        "status-failed": "#ba1a1a",
        "status-review": "#f59e0b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1440px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "12px", letterSpacing: "0.15em", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
